### ISSUE TITLE
Add VO to UploadClient (and maybe others)

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#13]
UploadClient does not take VO as an argument. Check if it's needed (based on calls in tests) and add VO as an argument if necessary.

Also check other Client classes to see if they are missing the VO argument.

**Comment by patrick-austin** [comment]
UploadClient, DownloadClient and DQ2Client all lack VO as an argument (all others have it). Instead, the former two take a Client as an argument, and refer to this when they need to access the vo (i.e. `self.client.vo`). If one a Client isn't provided then one is created, and for DQ2Client a new one is always created upon init.
Up/DownloadClient are tested by test_download.py, which runs successfully in multi_vo mode. DQ2Client doesn't appear to be referenced (or tested) anywhere else.
