### ISSUE TITLE
super_root features

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#17]
- [ ] Core
  - [x] Add VO (including root account and corresponding identity)
  - [x] Recover identity for root
  - [x] VO exists _(Andrew)_
  - [x] List VOs _(Andrew)_
  - [x] Edit VO
  - [ ] Remove VO
- [ ] API
  - [x] Add VO
  - [x] List VOs _(Andrew)_
  - [x] Edit VO
  - [ ] Remove VO
- [x] Initialise super_root with VO 'def'

No REST, Client or CLI layer for super_root features. Super_root should not have permissions for administration within a specific VO (e.g. adding users).

**Comment by patrick-austin** [comment]
Functionality for adding VOs is already present, however permissions to do this may need to be altered (and considered for the other features such as listing VOs) based on how the `super_root` is set up.

**Comment by patrick-austin** [comment]
Adding `super_root` account to `'def'` when `multi_vo == True` is already handled by `lib/rucio/db/sqla/util.py create_root_account`, which is called by `tools/bootstrap.py` and `tools/reset_database.py`.

**Comment by patrick-austin** [comment]
Follow discussion with Martin, have decided not to implement a VO deletion feature. Practically it would require disabling all accounts/RSEs associated with the VO before it could be deleted/suspended, and in doing so the VO would be rendered effectively functionless anyway.
