### ISSUE TITLE
Multi-VO Kibana dashboards

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#23]
Index events based on VO in Hermes message.

Restrict access to dashboards to only people from that VO? Requires setting up login, security etc.

**Comment by patrick-austin** [comment]
Reaper messages were missing the VO, resolved by #3950 (part of the 1.23.5 release)

The ELK stack now indexes by VO where present, set up dashboards that match the index pattern for a specific VO, and security with roles that only allow read only access for specific index patterns (and therefore VOs).
