### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#25]
- [x] super_root features
- [x] same name, separate VOs for account/scope/RSE
- [x] whole test suite on one VO and then another
- [x] user-facing functions return external representations
- [x] user authentication to specific VO (via each auth method)
- [x] single-VO daemons for each of two VOs.

If these get too complex, we can add a specific Travis container for multi-VO testing.

**Comment by patrick-austin** [comment]
Have added a test for automatix to ensure that it only acts on the VO that it was run from (as it uses client level functions) and does not inject files at a second VO with the same RSE and scope name.
The other "single VO" daemons that use the client (C3PO and sonar) have been deemed unused at development meetings and so don't need working on.

**Comment by patrick-austin** [comment]
It turns out that due to a bug in `rsemanager.upload` / the way `automatix` handles the return from it, the test of automatix will fail 1/4 times. This is not a m-VO issue, but given that there isn't a test of automatix in the main suite, it won't cause test failures there.
