### ISSUE TITLE
Client() calls in tests

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#4]
Calls to Client() (or other Client classes e.g. RSEClient) pick the VO up from the Rucio config file if a VO is not passed in as an argument. Check that this works properly when running tests in a multi-VO setting.

**Comment by patrick-austin** [comment]
Have run tests involving different Client classes (Replica, DID, Rule, Base) passing `vo=None`. Each goes through the code in BaseClient, and gets the VO from the config file successfully (I've not seen it successfully get it from the environ by `self.vo = environ['RUCIO_VO']` though). The tests then pass successfully.
