### ISSUE TITLE
Scripts to convert single-VO to multi-VO (and vice-versa?)

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#66]
Motivation
----------
A single-VO instance may want to expand to support more VOs. This should be possible without needing to create an entirely new Rucio instance and copy all the original data over.

If a VO becomes large, it may wish to split off from a multi-VO instance into its own single-VO instance.

Modification
------------
Write a script to change the VO associated with accounts, scopes and RSEs in the database on a single-VO instance.

Consider how a VO can be split off into a new multi-VO instance.

**Comment by elichad** [comment]
During this, consider that the value of `SCOPE_LENGTH` may need to be increased to accommodate the extra 4 characters for the VO.

**Comment by patrick-austin** [comment]
Resolved by #3926, #3966
