### ISSUE TITLE
Display VO descriptions

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#68]
Motivation
----------
It's potentially useful to be able to see VO descriptions at login time or when listing VOs. Discuss with Martin if this is worth adding to e.g. `list_vos` / CLI / webUI.

Modification
----------
TBC

**Comment by elichad** [comment]
Discussed with Martin.  It is not desirable to be able to figure out what VOs exist at login time - instead, try to authenticate with identity (+ optional account name) and then provide a drop down list of VOs (or account + VO combinations) if more than one is available.

**Comment by patrick-austin** [comment]
Added dropdown list to WebUI which displays VO identifier and description (but only when identity isn't unique to a VO) as part of PR [3886](https://github.com/rucio/rucio/pull/3886).
