### ISSUE TITLE
DIDType

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#7]
Does not use InternalScope, but instead just a scope name - does it need VO adding as an argument, or conversion to InternalScope? Discuss with Martin before making changes.

Also update references as necessary.

**Comment by patrick-austin** [comment]
Discussed with Martin. DIDType is (was) a prototype for handling different ways of specifying `scope` and `name`. Currently, there is one implementation in `DownloadClient` that doesn't pass anything deeper (only uses it as a string) and a test file (`test_didtype.py`). As a result this is not something that needs any further work.
