### ISSUE TITLE
Add Multi-VO template config files to Docker dev container

### ISSUE THREAD

**Issue by elichad** [stfc/rucio#85]
Motivation
----------
When running Multi-VO tests, the description looks for certain config files. These files should be added to the dev container by default.

Modification
------------
Make a pull request against [rucio/containers](https://github.com/rucio/containers) to copy these files into the dev container during the build process.

**Comment by patrick-austin** [comment]
This (along with enabling the m-VO config options to be passed as env variables) was merged into [rucio/containers](https://github.com/rucio/containers) as PR 84.
